package-lock.json, package.json, src/config/routes.js, src/modules/users/user.model.js, src/modules/users/users.routes.js, src/modules/users/users.service.js
Criação da requisição de cadastro de usuários.
=> mytasks-4: Criação da requisição de cadastro de usuários

src/modules/users/users.routes.js, src/modules/users/users.service.js, swagger.json
Criação da requisição de login.
=> mytasks-2: Criação da requisição de login

src/modules/users/users.routes.js, src/modules/users/users.service.js, swagger.json
Criação da request para listar os usuários.
=> mytasks-19: Criação da request para listar os usuários

src/config/routes.js, src/modules/groups/group.model.js, src/modules/groups/groups.routes.js, src/modules/groups/groups.service.js, swagger.json
Criação da request para adicionar um grupo de tarefas.
=> mytasks-10: Criação da request para adicionar um grupo de tarefas

src/modules/users/users.routes.js, src/modules/users/users.service.js, swagger.json
Criação da request para editar as informações do usuário.
=> mytasks-5: Criação da request para editar as informações do usuário

src/modules/groups/groups.routes.js, src/modules/groups/groups.service.js
Criação da request para listar as tarefas de um usuário.
=> mytasks-9: Criação da request para listar as tarefas de um usuário

src/modules/groups/groups.routes.js, src/modules/groups/groups.service.js
Criação da request para editar um grupo de tarefas.
=> mytasks-11: Criação da request para editar um grupo de tarefas

src/modules/groups/groups.routes.js, src/modules/groups/groups.service.js
Criação da request para deletar um grupo de tarefas.
=> mytasks-12: Criação da request para deletar um grupo de tarefas

src/modules/users/users.routes.js, src/modules/users/users.service.js
Criação da request para adicionar um amigo.
=> mytasks-15: Criação da request para adicionar um amigo

src/modules/users/user.model.js, src/modules/users/users.service.js
Atualização no model e em algumas requests do usuários.
Mudanças:
- Adicionado o array de amigos no model
- Adicionado o id no retorno do login
- Mudança de nome de propriedade ao adicionar um amigo
=> mytasks-20: Atualização no model e em algumas requests do usuários

src/config/routes.js
Atualização no import do arquivo swagger.json
=> mytasks-21: Atualização no import do arquivo swagger.json

src/modules/users/users.routes.js, src/modules/users/users.service.js
Criação da request para buscar amigos.
=> mytasks-14: Criação da request para buscar amigos

src/modules/users/users.routes.js, src/modules/users/users.service.js
Criação da request para deletar um amigo.
=> mytasks-16: Criação da request para deletar um amigo

src/modules/tasks/tasks.routes.js, src/modules/tasks/tasks.service.js
Criação da request para deletar uma tarefa
=> mytasks-8: Criação da request para deletar uma tarefa

src/modules/tasks/tasks.routes.js, src/modules/tasks/tasks.service.js
Criação da request para editar uma tarefa
=> mytasks-7: Criação da request para editar uma tarefa

src/modules/tasks/tasks.routes.js, src/modules/tasks/tasks.service.js
Criação da request para listar as tarefas de um usuário
=> mytasks-9: Criação da request para listar as tarefas de um usuário 

src/modules/groups/group.model.js, src/modules/groups/groups.routes.js, src/modules/groups/groups.service.js, src/modules/users/users.service.js
Atualização nas requisições de grupo.
=> mytasks-22: Atualização nas requisições de grupo

src/modules/groups/groups.routes.js, src/modules/groups/groups.service.js, src/modules/tasks/task.model.js, src/modules/tasks/tasks.routes.js, src/modules/tasks/tasks.service.js
Atualização nas requests de grupos e tarefas.
=> mytasks-23: Atualização nas requests de grupos e tarefas

src/modules/tasks/task.model.js, src/modules/tasks/tasks.routes.js, src/modules/tasks/tasks.service.js
Criação da request para buscar uma tarefa.
=> mytasks-24: Criação da request para buscar uma tarefa

src/modules/groups/groups.routes.js, src/modules/groups/groups.service.js
Criação da request para buscar um grupo.
=> mytasks-25: Criação da request para buscar um grupo
